ws1 = 0.2*pi;
ws2 = 0.8*pi;
wp1 = 0.35*pi; 
wp2 = 0.65*pi;
tr_width = wp1-ws1;
wc1 = (ws1+wp1)/2;
wc2 = (ws2+wp2)/2;
N = ceil(11*pi/tr_width)+1;
n = 0:N-1;
alpha = (N-1)/2;
hd = (wc2/pi)*sinc((wc2/pi)*(n-alpha))-(wc1/pi)*sinc((wc1/pi)*(n-alpha));
w_blackman = blackman(N)';
h = hd.*w_blackman;
subplot(221);
stem(n, hd, 'filled');
axis tight;
xlabel('n');
ylabel('hd(n)');
[Hr,w1] = zerophase(h);
subplot(222);
plot(w1/pi,Hr);
axis tight;
xlabel('\omega/\pi');
ylabel('H(\omega)');
subplot(223);
stem(n,h,'filled');
axis tight;
xlabel('n');
ylabel('h(n)');
[H,w] = freqz(h, 1);
subplot(224);
plot(w/pi,20*log10(abs(H)/max(abs(H))));
xlabel('\omega/\pi');
ylabel('dB');
grid on;
