%矩形窗
wp=0.2*pi;
wst=0.3*pi;
tr_width=wst-wp;
N = ceil(1.8*pi/tr_width)+1;
n = 0:N-1;
wc = (wp+wst)/2;
alpha = (N-1)/2;
hd = (wc/pi)*sinc((wc/pi) * (n-alpha));
w_boxcar = boxcar(N)';
h = hd.*w_boxcar;
subplot(221);
stem(n,hd,'filled');
axis tight;
xlabel('n');
ylabel('hd(n)');
[Hr,w1] = zerophase(h);
subplot(222);
plot(w1/pi,Hr);
axis tight;
xlabel('\omega/\pi');
ylabel('H(\omega)');
subplot(223);
stem(n,h,'filled');
axis tight;
xlabel('n');
ylabel('h(n)');
[H,w] = freqz(h,1);
subplot(224);
plot(w/pi,20*log10(abs(H)/max(abs(H))));
xlabel('\omega/\pi');
ylabel('dB');
grid on;
